name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cargo build --verbose
    - name: clippy
      run: cargo clippy
    - name: fmt
      run: cargo fmt --all -- --check
    - name: Run tests
      run: cargo test --verbose
